# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  chatbot:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ./
      dockerfile: ./Dockerfile
    image: ${REGISTRY:-opea}/chatbot:${TAG:-latest}
  whisper:
    build:
      context: ../
      dockerfile: opea-comps/deps/asr/src/integrations/dependency/whisper/Dockerfile
    extends: chatbot
    image: ${REGISTRY:-opea}/whisper:${TAG:-latest}
  asr:
    build:
      context: ../
      dockerfile: opea-comps/deps/asr/src/Dockerfile
    extends: chatbot
    image: ${REGISTRY:-opea}/asr:${TAG:-latest}
  llm-textgen:
    build:
      context: ../
      dockerfile: opea-comps/deps/llm/text-generation/Dockerfile
    extends: chatbot
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
  speecht5:
    build:
      context: ../
      dockerfile: opea-comps/deps/tts/src/integrations/dependency/speecht5/Dockerfile
    extends: chatbot
    image: ${REGISTRY:-opea}/speecht5:${TAG:-latest}
  tts:
    build:
      context: ../
      dockerfile: opea-comps/deps/tts/src/Dockerfile
    extends: chatbot
    image: ${REGISTRY:-opea}/tts:${TAG:-latest}